# Generated by Django 3.0.4 on 2020-03-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('content', models.BinaryField(null=True)),
                ('filesize', models.IntegerField(null=None)),
                ('content_type', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
                ('result', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('WORKING', 'Working'), ('DONE', 'Done')], default='IDLE', max_length=7)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.File')),
            ],
        ),
    ]
